#!/sbin/busybox sh
#
## Save orig. path
_PATH="$PATH"
export PATH=/sbin

cd /
busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

## Logging??
busybox date >/boot-debug.log
exec >>/boot-debug.log 2>&1

## Bootmode
echo "Checking BootMode ..." >> /boot-debug.log
BMODE=System

## Recovery Boot
if grep -q bootmode=2 /proc/cmdline ; then
  rm /init.rc
  cp /recovery.rc /init.rc
  BMODE=Recovery
fi

## Low Power Mode
if grep -q 1 /sys/class/power_supply/battery/batt_lp_charging ; then
  rm /init.rc
  cp /lpm.rc /init.rc
  BMODE=LowPower
fi

## Create basic devs
mkdir -p /dev/block
mkdir /dev/input
mkdir /dev/graphics
mknod /dev/graphics/fb0 c 29 0
mknod /dev/input/event1 c 13 65
mknod /dev/input/event2 c 13 66
mknod /dev/input/event8 c 13 72
mknod /dev/input/event9 c 13 73
mknod /dev/ashmem c 10 61
mknod /dev/block/mmcblk0p7 b 179 7
mknod /dev/block/mmcblk0p9 b 259 1
mknod /dev/block/mmcblk0p10 b 259 2
mknod /dev/block/mmcblk0p11 b 259 3
mknod /dev/block/mmcblk0p12 b 259 4
mknod /dev/block/loop0 b 7 0

busybox mount -t ext4 /dev/block/mmcblk0p9 /system

AOSP=0
[ -f /system/framework/framework2.jar ] || AOSP=1
[ "`/sbin/busybox grep Slim /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i aosp /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i hydrog /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i =aokp /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i CyanogenMod /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i AdyScorpius /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i cMIUI /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i insanity /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i Oxygen /system/build.prop`" ] && AOSP=1

if [ "$AOSP" == 1 ];
then
  BMODE=System-AOSP
  # Remove Stock rc's
  rm /default.prop
  rm /init.goldfish.rc
  rm /init.rc
  rm /init.smdk4210.rc
  rm /init.smdk4210.usb.rc
  rm /ueventd.rc
  rm /ueventd.smdk4210.rc
  # Copy over AOSP rc's
  cp -ax /res/misc/aosp/* /
else
  BMODE=System-Stock
fi;

busybox umount /system
busybox umount /sys
busybox umount /proc

busybox date >>/boot-debug.log
echo "Booting up with BootMode: ${BMODE}" >> /boot-debug.log

## restore old path
export PATH="${_PATH}"
rm -rf /dev/*

## remove symlink and execute init
rm /init
mv /innt /init
exec /init
